### ISSUE TITLE
The new vue-play-cli 

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play-cli#1]
### generate a sample play app in user's project

let's say `./play`, inside the folder: 

#### entry file for loading scenarios (not webpack entry), where we load all scenarios: (a.k.a. stories in react-storybook)
```js
import {configure} from 'vue-play'
// dynamically loading
const load = requireContext => {
  return requireContext.keys().map(requireContext)
}

const scenarios = load(require.context('./', true, /.play.js$/))

configure(scenarios, module)
```
### development mode

webpack-dev-server?

## Commands

- `vue-play init`: generate sample folder, throw warning if `./play` exists
- `vue-play start`: Run webpack server
- `vue-play build`: Run webpack

---

*Open to discussion*

**Comment by egoist** [comment]
The webpack entry should be https://github.com/vue-play/vue-play/blob/3dc284044624fb0a0d3a3770f026725ad59a8a12/README.md#the-hard-way

These files could be put in `vue-play-cli` instead of user's project

**Comment by egoist** [comment]
eh, maybe use webpack 1

webpack 2 is sometimes too troublesome 😅

**Comment by just-be-dev** [comment]
So just so I understand, I need to generate a `play` directory with an entry point for the application.  Do we also generate out a webpack config file?

**Comment by egoist** [comment]
I guess no, we just need to figure out the way to merge custom config

**Comment by just-be-dev** [comment]
This no longer needs to be done, right? If so, we can close it. Sorry I never got to it.
