### ISSUE TITLE
HMR broken with vue-cli project?

### ISSUE THREAD

**Issue by dweldon** [vue-play/vue-play-cli#3]
I'm using v1.0.2 with a setup described on [my blog](https://dweldon.silvrback.com/vue-play). When the app starts I get this in the console:

    [Vue warn]: Cannot find element: #app 

Then after modifying one of the scenarios I get this:

    app.js:802 Uncaught RangeError: Maximum call stack size exceeded
    [HMR] The following modules couldn't be hot updated: (Full reload needed)
    ...
    VM729:89 [HMR]  - ./src/play/scenarios/Icon.js

Everything works except HMR. Any ideas?

**Comment by egoist** [comment]
> [Vue warn]: Cannot find element: #app 

I think you've solved this, right?

And hmr is only working with single file component now, I kinda need some help on making hmr work with js components and `play files`. check out https://github.com/vuejs/vue-requests/issues/18

**Comment by dweldon** [comment]
Oh I see - the components will hot reload, but the scenario files do not. I'd recommend putting that in a "known issues" section of one of the readme files so others don't get stuck on this.

I'm not sure about that `#app` error. It's different than the one I had before, but it doesn't seem to be causing any harm so I'm choosing to ignore it. :see_no_evil:

**Comment by egoist** [comment]
I just added `live reload` for files that can't hot reload (only the iframe will be reloaded)

btw, can you share the repo which caused the `Cannot find element: #app` error?

**Comment by dweldon** [comment]
Nice work on the reload change. `1.0.3` is much more user friendly.

[Here is a reproduction of the error](https://github.com/dweldon/play-cli-error). As the readme points out, it's basically a stock `vue-cli` project with `vue-play-cli` and a simple scenario.

**Comment by egoist** [comment]
I guess I've found out the reason, you should update the `html-webpack-plugin` options in your webpack config to:

``` js
new HtmlWebpackPlugin({
   filename: 'index.html',
   chunks: ['app']
}),
new HtmlWebpackPlugin({
  filename: 'preview.html',
  chunks: ['preview']
})
```

The main idea is to use `index.html` to load `app` chunk, and use `preview.html` to load `preview` chunk. Now you're using `index.html` to load both chunks, so `app` renders in `#app` and that element is gone, then the `preview` unexpectedly renders in `index.html` and cannot find that element.
